apiVersion: v1
kind: Service
metadata:
  name: spring3-devsecops
spec:
  selector:
    app: spring3-devsecops
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort