apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesJson6902:
  - target:
      kind: Deployment
      name: spring3-devsecops
      version: v1
      group: apps
    path: deployment-replace.yaml